name: horarios_transporte
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+10

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: 8.0.2
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.15.0  # Android implementation
  webview_flutter_wkwebview: ^3.15.0  # iOS/macOS implementation
  flutter_custom_tabs: ^2.0.0+1
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  get: ^4.6.5
  fluttertoast: ^8.2.2
  hive: ^2.1.0 
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  onesignal_flutter: ^5.2.0
  scrollable_positioned_list: ^0.3.8
  flutter_webview_plugin: ^0.4.0
  internet_connection_checker: ^1.0.0+1
  confirm_dialog: ^1.0.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.0.15
  dio: ^5.0.0
  cookie_jar: ^2.0.0
  dart_jsonwebtoken: ^2.14.0
  cpf_cnpj_validator: ^2.0.0 # Para validar e formatar CPF
  email_validator: ^2.0.1    # Para validar emails
  bcrypt: ^1.1.3            # Para gerar o hash da senha usando Bcrypt
  flutter_bloc: ^8.1.2
  equatable: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Custom
      fonts: 
        - asset: fonts/Custom-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/connectbuss.png"

flutter_native_splash:
  color: "#000000"
  image: images/connectbuss.png
